#
# OpenSCAD 3Dprint Project Template
# 20251222, Ondrej DURAS (dury) Nokia
# 
help:
	@echo "Use one of following:"
	@echo " make basic        # provides project visual in .PNG file"
	@echo " make variants     # provides visual of particular variats in a .PNG file"
	@echo " make movie        # provides .MP4 short movie visual"
	@echo " make plate        # provides .STL file for slicer"
	@echo " make clean        # removes all binary files (.STL, .PNG, .3MF, .MP4)"

clean:
	rm -vf 001-Tower2G-Experiment.stl

# --- end ---


